--CREATE TABLE fencing_actions (
--  id   BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--  boutSchemeType VARCHAR(255),
--);
--
--CREATE TABLE piste_zones (
--  id   BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--  boutSchemeType VARCHAR(255),
--);